version: '3.8'

services:
  nodered:
    image: nodered/node-red:latest
    container_name: nodered
    ports:
      - "1880:1880"   # Expose port 1880
    volumes:
      - ./node_red_data:/data
    restart: always
